version: 0.2

phases:
  # Install phase: Installing dependencies (Maven, Docker)
  install:
    runtime-versions:
      java: openjdk17  # Use Java 17 (or change it to your Java version)
    commands:
      # Installing Maven if it's not already available
      echo Installing Maven
  # Pre-build phase: Set up login for Amazon ECR
  pre_build:
    commands:
      # Log in to Amazon ECR repository using AWS CLI
      echo Logging in to Amazon ECR...
      $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      # Build the Java application using Maven (skip tests for faster build)
      echo Building the Java application...
      mvn clean install
