version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Installing Maven if it's not already available
  # Pre-build phase: Set up login for Amazon ECR
  pre_build:
    commands:
      # Log in to Amazon ECR repository using AWS CLI
      aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 443370689809.dkr.ecr.ap-south-1.amazonaws.com/javadeployment
  build:
    commands:
      # Build the Java application using Maven (skip tests for faster build)
      echo Building the Java application...
      mvn clean install
